#!/usr/bin/env bash

USERNAME="flcnr"
EMAIL="luisfalconeri@gmail.com"


echo "Creating a new project"
cd /Users/flcnr/Documents/Dev-new
NAME=${1?Error: no name given}
mkdir $NAME
cd $NAME
virtualenv .
source bin/activate
pip install django
django-admin.py startproject $NAME
mv /Users/flcnr/Documents/Dev-new/$NAME/$NAME  /Users/flcnr/Documents/Dev-new/$NAME/src
cd src
cd $NAME
mkdir settings
mv settings.py settings/settings.py
cd settings
echo "from .base import *
from .production import *

try:
   from .local import *
except:
   pass
" > __init__.py

#python manage.py migrate
#python manage.py createsuperuser --username $USERNAME --email $EMAIL
#python manage.py startapp mainapp
#git init
#git add .
#git commit -m "first automatic commit"
#cd mainapp
#python manage.py runserver
